name: Windows Tests (Without Integration Tests)

on: pull_request

jobs:
    windows-build:
        name: Tests on Windows
        runs-on: windows-latest
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v2

            -   name: Setup JDK
                uses: actions/setup-java@v2
                with:
                    distribution: 'adopt'
                    java-version: 8

            -   name: Initialize Submodules
                run: |
                    git submodule update --init

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '10.22.1'

            -   name: Build Ballerina Lang
                run: |
                    git submodule init
                    git submodule update
                    ./gradlew.bat build --no-parallel -x :ballerina-packerina:test -x :ballerina-lang:test -x :ballerina-file:test -x :ballerina-socket:test -x :jballerina-unit-test:test -x :jballerina-integration-test:test -x :ballerina-mysql:test -x :plugin-vscode:test -x createJavadoc --stacktrace -scan --console=plain --no-daemon
